name: Sheetswiper - Build and Test

on: 
  push:

jobs:
  build-and-test:
    name: Build and Run Tests
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore
        run: dotnet restore src/SheetSwiper.sln
      
      - name: Build
        run: dotnet build src/SheetSwiper.sln --no-restore

      - name: Run NUnit Tests
        run: dotnet test src/SheetSwiper.sln